tiers: 1v1 # feel free to supply an array

poll_length: 10 # time between checking for new battles

socket: ws://sim.smogon.com:8000/showdown/websocket # if you don't know what this is, don't touch it
